<?php

use App\Models\Fligths\Country;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::create(['id' => 1, 'name' => "Afghanistan"]);
        Country::create(['id' => 2, 'name' => "Albania"]);
        Country::create(['id' => 3, 'name' => "Algeria"]);
        Country::create(['id' => 4, 'name' => "Angola"]);
        Country::create(['id' => 5, 'name' => "Anguilla"]);
        Country::create(['id' => 6, 'name' => "Antarctica"]);
        Country::create(['id' => 7, 'name' => "Antigua And Barbuda"]);
        Country::create(['id' => 8, 'name' => "Argentina"]);
        Country::create(['id' => 9, 'name' => "Armenia"]);
        Country::create(['id' => 10, 'name' => "Aruba"]);
        Country::create(['id' => 11, 'name' => "Australia"]);
        Country::create(['id' => 12, 'name' => "Austria"]);
        Country::create(['id' => 13, 'name' => "Azerbaijan"]);
        Country::create(['id' => 14, 'name' => "Bahamas"]);
        Country::create(['id' => 15, 'name' => "Bahrain"]);
        Country::create(['id' => 16, 'name' => "Bangladesh"]);
        Country::create(['id' => 17, 'name' => "Barbados"]);
        Country::create(['id' => 18, 'name' => "Belarus"]);
        Country::create(['id' => 19, 'name' => "Belgium"]);
        Country::create(['id' => 20, 'name' => "Belize"]);
        Country::create(['id' => 21, 'name' => "Benin"]);
        Country::create(['id' => 22, 'name' => "Bermuda"]);
        Country::create(['id' => 23, 'name' => "Bhutan"]);
        Country::create(['id' => 24, 'name' => "Bolivia"]);
        Country::create(['id' => 25, 'name' => "Bosnia And Herzegovina"]);
        Country::create(['id' => 26, 'name' => "Botswana"]);
        Country::create(['id' => 27, 'name' => "Brazil"]);
        Country::create(['id' => 28, 'name' => "Brunei"]);
        Country::create(['id' => 29, 'name' => "Bulgaria"]);
        Country::create(['id' => 30, 'name' => "Burkina Faso"]);
        Country::create(['id' => 31, 'name' => "Burundi"]);
        Country::create(['id' => 32, 'name' => "Cambodia"]);
        Country::create(['id' => 33, 'name' => "Cameroon"]);
        Country::create(['id' => 34, 'name' => "Canada"]);
        Country::create(['id' => 35, 'name' => "Cape Verde"]);
        Country::create(['id' => 36, 'name' => "Cayman Islands"]);
        Country::create(['id' => 37, 'name' => "Central African Republic"]);
        Country::create(['id' => 38, 'name' => "Chad"]);
        Country::create(['id' => 39, 'name' => "Chile"]);
        Country::create(['id' => 40, 'name' => "China"]);
        Country::create(['id' => 41, 'name' => "Cocos (Keeling) Islands"]);
        Country::create(['id' => 42, 'name' => "Colombia"]);
        Country::create(['id' => 43, 'name' => "Comoros"]);
        Country::create(['id' => 44, 'name' => "Congo"]);
        Country::create(['id' => 45, 'name' => "Cook Islands"]);
        Country::create(['id' => 46, 'name' => "Costa Rica"]);
        Country::create(['id' => 47, 'name' => "Cote D'ivoire (Ivory Coast)"]);
        Country::create(['id' => 48, 'name' => "Croatia"]);
        Country::create(['id' => 49, 'name' => "Cuba"]);
        Country::create(['id' => 50, 'name' => "Curacao"]);
        Country::create(['id' => 51, 'name' => "Cyprus"]);
        Country::create(['id' => 52, 'name' => "Czechia"]);
        Country::create(['id' => 53, 'name' => "Democratic Republic Of The Congo"]);
        Country::create(['id' => 54, 'name' => "Denmark"]);
        Country::create(['id' => 55, 'name' => "Djibouti"]);
        Country::create(['id' => 56, 'name' => "Dominica"]);
        Country::create(['id' => 57, 'name' => "Dominican Republic"]);
        Country::create(['id' => 58, 'name' => "Ecuador"]);
        Country::create(['id' => 59, 'name' => "Egypt"]);
        Country::create(['id' => 60, 'name' => "El Salvador"]);
        Country::create(['id' => 61, 'name' => "Equatorial Guinea"]);
        Country::create(['id' => 62, 'name' => "Eritrea"]);
        Country::create(['id' => 63, 'name' => "Estonia"]);
        Country::create(['id' => 64, 'name' => "Ethiopia"]);
        Country::create(['id' => 65, 'name' => "Falkland Islands (Malvinas)"]);
        Country::create(['id' => 66, 'name' => "Faroe Islands"]);
        Country::create(['id' => 67, 'name' => "Fiji"]);
        Country::create(['id' => 68, 'name' => "Finland"]);
        Country::create(['id' => 69, 'name' => "France"]);
        Country::create(['id' => 70, 'name' => "French Guiana"]);
        Country::create(['id' => 71, 'name' => "French Polynesia"]);
        Country::create(['id' => 72, 'name' => "Gabon"]);
        Country::create(['id' => 73, 'name' => "Gambia"]);
        Country::create(['id' => 74, 'name' => "Georgia"]);
        Country::create(['id' => 75, 'name' => "Germany"]);
        Country::create(['id' => 76, 'name' => "Ghana"]);
        Country::create(['id' => 77, 'name' => "Gibraltitudear"]);
        Country::create(['id' => 78, 'name' => "Greece"]);
        Country::create(['id' => 79, 'name' => "Greenland"]);
        Country::create(['id' => 80, 'name' => "Grenada"]);
        Country::create(['id' => 81, 'name' => "Guadeloupe"]);
        Country::create(['id' => 82, 'name' => "Guam"]);
        Country::create(['id' => 83, 'name' => "Guatemala"]);
        Country::create(['id' => 84, 'name' => "Guinea"]);
        Country::create(['id' => 85, 'name' => "Guinea-Bissau"]);
        Country::create(['id' => 86, 'name' => "Guyana"]);
        Country::create(['id' => 87, 'name' => "Haiti"]);
        Country::create(['id' => 88, 'name' => "Honduras"]);
        Country::create(['id' => 89, 'name' => "Hong Kong"]);
        Country::create(['id' => 90, 'name' => "Hungary"]);
        Country::create(['id' => 91, 'name' => "Iceland"]);
        Country::create(['id' => 92, 'name' => "India"]);
        Country::create(['id' => 93, 'name' => "Indonesia"]);
        Country::create(['id' => 94, 'name' => "Iran"]);
        Country::create(['id' => 95, 'name' => "Iraq"]);
        Country::create(['id' => 96, 'name' => "Ireland"]);
        Country::create(['id' => 97, 'name' => "Israel"]);
        Country::create(['id' => 98, 'name' => "Italy"]);
        Country::create(['id' => 99, 'name' => "Jamaica"]);
        Country::create(['id' => 100, 'name' => "Japan"]);
        Country::create(['id' => 101, 'name' => "Jordan"]);
        Country::create(['id' => 102, 'name' => "Kazakhstan"]);
        Country::create(['id' => 103, 'name' => "Kenya"]);
        Country::create(['id' => 104, 'name' => "Kiribati"]);
        Country::create(['id' => 105, 'name' => "Kosovo"]);
        Country::create(['id' => 106, 'name' => "Kuwait"]);
        Country::create(['id' => 107, 'name' => "Kyrgyzstan"]);
        Country::create(['id' => 108, 'name' => "Laos"]);
        Country::create(['id' => 109, 'name' => "latitudevia"]);
        Country::create(['id' => 110, 'name' => "Lebanon"]);
        Country::create(['id' => 111, 'name' => "Lesotho"]);
        Country::create(['id' => 112, 'name' => "Liberia"]);
        Country::create(['id' => 113, 'name' => "Libya"]);
        Country::create(['id' => 114, 'name' => "Lithuania"]);
        Country::create(['id' => 115, 'name' => "Luxembourg"]);
        Country::create(['id' => 116, 'name' => "Macao"]);
        Country::create(['id' => 117, 'name' => "Madagascar"]);
        Country::create(['id' => 118, 'name' => "Malawi"]);
        Country::create(['id' => 119, 'name' => "Malaysia"]);
        Country::create(['id' => 120, 'name' => "Maldives"]);
        Country::create(['id' => 121, 'name' => "Mali"]);
        Country::create(['id' => 122, 'name' => "Maltitudea"]);
        Country::create(['id' => 123, 'name' => "Marshall Islands"]);
        Country::create(['id' => 124, 'name' => "Martinique"]);
        Country::create(['id' => 125, 'name' => "Mauritania"]);
        Country::create(['id' => 126, 'name' => "Mauritius"]);
        Country::create(['id' => 127, 'name' => "Mayotte"]);
        Country::create(['id' => 128, 'name' => "Mexico"]);
        Country::create(['id' => 129, 'name' => "Micronesia"]);
        Country::create(['id' => 130, 'name' => "Moldova"]);
        Country::create(['id' => 131, 'name' => "Monaco"]);
        Country::create(['id' => 132, 'name' => "Mongolia"]);
        Country::create(['id' => 133, 'name' => "Montenegro"]);
        Country::create(['id' => 134, 'name' => "Montserrat"]);
        Country::create(['id' => 135, 'name' => "Morocco"]);
        Country::create(['id' => 136, 'name' => "Mozambique"]);
        Country::create(['id' => 137, 'name' => "Myanmar (Burma)"]);
        Country::create(['id' => 138, 'name' => "Namibia"]);
        Country::create(['id' => 139, 'name' => "Nauru"]);
        Country::create(['id' => 140, 'name' => "Nepal"]);
        Country::create(['id' => 141, 'name' => "Netherlands"]);
        Country::create(['id' => 142, 'name' => "New Caledonia"]);
        Country::create(['id' => 143, 'name' => "New Zealand"]);
        Country::create(['id' => 144, 'name' => "Nicaragua"]);
        Country::create(['id' => 145, 'name' => "Niger"]);
        Country::create(['id' => 146, 'name' => "Nigeria"]);
        Country::create(['id' => 147, 'name' => "North Korea"]);
        Country::create(['id' => 148, 'name' => "North Macedonia"]);
        Country::create(['id' => 149, 'name' => "Northern Mariana Islands"]);
        Country::create(['id' => 150, 'name' => "Norway"]);
        Country::create(['id' => 151, 'name' => "Oman"]);
        Country::create(['id' => 152, 'name' => "Pakistan"]);
        Country::create(['id' => 153, 'name' => "Palau"]);
        Country::create(['id' => 154, 'name' => "Panama"]);
        Country::create(['id' => 155, 'name' => "Papua New Guinea"]);
        Country::create(['id' => 156, 'name' => "Paraguay"]);
        Country::create(['id' => 157, 'name' => "Peru"]);
        Country::create(['id' => 158, 'name' => "Philippines"]);
        Country::create(['id' => 159, 'name' => "Poland"]);
        Country::create(['id' => 160, 'name' => "Portugal"]);
        Country::create(['id' => 161, 'name' => "Puerto Rico"]);
        Country::create(['id' => 162, 'name' => "Qatar"]);
        Country::create(['id' => 163, 'name' => "Reunion"]);
        Country::create(['id' => 164, 'name' => "Romania"]);
        Country::create(['id' => 165, 'name' => "Russia"]);
        Country::create(['id' => 166, 'name' => "Rwanda"]);
        Country::create(['id' => 167, 'name' => "Saint Helena"]);
        Country::create(['id' => 168, 'name' => "Saint Kitts And Nevis"]);
        Country::create(['id' => 169, 'name' => "Saint Lucia"]);
        Country::create(['id' => 170, 'name' => "Saint Pierre And Miquelongitude"]);
        Country::create(['id' => 171, 'name' => "Saint Vincent And The Grenadines"]);
        Country::create(['id' => 172, 'name' => "Samoa"]);
        Country::create(['id' => 173, 'name' => "Sao Tome And Principe"]);
        Country::create(['id' => 174, 'name' => "Saudi Arabia"]);
        Country::create(['id' => 175, 'name' => "Senegal"]);
        Country::create(['id' => 176, 'name' => "Serbia"]);
        Country::create(['id' => 177, 'name' => "Seychelles"]);
        Country::create(['id' => 178, 'name' => "Sierra Leone"]);
        Country::create(['id' => 179, 'name' => "Singapore"]);
        Country::create(['id' => 180, 'name' => "Slovakia"]);
        Country::create(['id' => 181, 'name' => "Slovenia"]);
        Country::create(['id' => 182, 'name' => "Solomon Islands"]);
        Country::create(['id' => 183, 'name' => "Somalia"]);
        Country::create(['id' => 184, 'name' => "South Africa"]);
        Country::create(['id' => 185, 'name' => "South Korea"]);
        Country::create(['id' => 186, 'name' => "Spain"]);
        Country::create(['id' => 187, 'name' => "Sri Lanka"]);
        Country::create(['id' => 188, 'name' => "Sudan"]);
        Country::create(['id' => 189, 'name' => "Suriname"]);
        Country::create(['id' => 190, 'name' => "Swaziland"]);
        Country::create(['id' => 191, 'name' => "Sweden"]);
        Country::create(['id' => 192, 'name' => "Switzerland"]);
        Country::create(['id' => 193, 'name' => "Syria"]);
        Country::create(['id' => 194, 'name' => "Taiwan"]);
        Country::create(['id' => 195, 'name' => "Tajikistan"]);
        Country::create(['id' => 196, 'name' => "Tanzania"]);
        Country::create(['id' => 197, 'name' => "Thailand"]);
        Country::create(['id' => 198, 'name' => "Timor-Leste (East Timor)"]);
        Country::create(['id' => 199, 'name' => "Togo"]);
        Country::create(['id' => 200, 'name' => "Tonga"]);
        Country::create(['id' => 201, 'name' => "Trinidad And Tobago"]);
        Country::create(['id' => 202, 'name' => "Tunisia"]);
        Country::create(['id' => 203, 'name' => "Turkey"]);
        Country::create(['id' => 204, 'name' => "Turkmenistan"]);
        Country::create(['id' => 205, 'name' => "Turks And Caicos Islands"]);
        Country::create(['id' => 206, 'name' => "Tuvalu"]);
        Country::create(['id' => 207, 'name' => "Uganda"]);
        Country::create(['id' => 208, 'name' => "Ukraine"]);
        Country::create(['id' => 209, 'name' => "United Arab Emirates"]);
        Country::create(['id' => 210, 'name' => "United Kingdom"]);
        Country::create(['id' => 211, 'name' => "United States"]);
        Country::create(['id' => 212, 'name' => "Uruguay"]);
        Country::create(['id' => 213, 'name' => "Uzbekistan"]);
        Country::create(['id' => 214, 'name' => "Vanuatu"]);
        Country::create(['id' => 215, 'name' => "Venezuela"]);
        Country::create(['id' => 216, 'name' => "Vietnam"]);
        Country::create(['id' => 217, 'name' => "Virgin Islands, British"]);
        Country::create(['id' => 218, 'name' => "Virgin Islands, Us"]);
        Country::create(['id' => 219, 'name' => "Wallis And Futuna"]);
        Country::create(['id' => 220, 'name' => "Yemen"]);
        Country::create(['id' => 221, 'name' => "Zambia"]);
        Country::create(['id' => 222, 'name' => "Zimbabwe"]);
    }
}
